apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-frontend
  namespace: restaurant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restaurant-frontend
  template:
    metadata:
      labels:
        app: restaurant-frontend
    spec:
      containers:
      - name: restaurant-frontend
        image: restaurant-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.your-domain.com/api"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-frontend
  namespace: restaurant
spec:
  selector:
    app: restaurant-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP